anguage: java

jdk:
  - openjdk11

branches:
  only:
    - master

script:
  - mvn clean package -DskipTests

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
